### ISSUE TITLE
App crash after a successful  build on ANDROID

### ISSUE THREAD

**Issue by YoniCosta** [Appboy/appboy-react-sdk#113]
error message in android studio

E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.greenlabs.smartfarm, PID: 9463
    java.lang.NoSuchMethodError: No static method getInstance(Landroid/content/Context;)Lcom/appboy/Appboy; in class Lcom/appboy/Appboy; or its super classes (declaration of 'com.appboy.Appboy' appears in /data/app/com.greenlabs.smartfarm-maquPehEjhn1mslOGLCSWQ==/base.apk)
        at com.appboy.reactbridge.AppboyReactBridge.subscribeToContentCardsUpdatedEvent(AppboyReactBridge.java:691)
        at com.appboy.reactbridge.AppboyReactBridge.<init>(AppboyReactBridge.java:72)
        at com.appboy.reactbridge.AppboyReactPackage.createNativeModules(AppboyReactPackage.java:21)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1215)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1185)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1123)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:124)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:948)
        at java.lang.Thread.run(Thread.java:919)

on com.appboy:android-sdk-ui 13.1.0 working fine.

**Comment by francoSimeone** [comment]
I am having the same exact problem

**Comment by Bucimis** [comment]
Hi @francoSimeone and @YoniCosta, we recommend using the same version of the Braze Android SDK used by the latest version of the Braze React Native SDK, currently 13.1.2 (see https://github.com/Appboy/appboy-react-sdk/blob/master/android/build.gradle#L20).

To fix, replace
```
implementation "com.appboy:android-sdk-ui:+"
```
with
```
implementation "com.appboy:android-sdk-ui:13.1.2"
```
to your build.gradle.

We will update our React Native integration to support Braze Android SDK 14+ in the coming weeks.

**Comment by radixdev** [comment]
The native bridge has been updated for android 14.0.0+
