### ISSUE TITLE
Android crash: No static method getInstance

### ISSUE THREAD

**Issue by mattdamon108** [Appboy/appboy-react-sdk#114]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [x] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

v14.0

## What did you do?

Initial SDK setup

## What did you expect to happen?

Running my React Native app properly

## What happened instead?

App is crashed after successful build.

## Steps to reproduce

1. Add dependency `react-native-appboy-sdk@latest`
2. Follow the initial SDK setup guide for react native and android
3. Build and run

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No

## Project that demonstrates the issue

# ANR Reporting

## Braze Related Threads In ANR

error message in android studio

```
E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.greenlabs.smartfarm, PID: 9463
    java.lang.NoSuchMethodError: No static method getInstance(Landroid/content/Context;)Lcom/appboy/Appboy; in class Lcom/appboy/Appboy; or its super classes (declaration of 'com.appboy.Appboy' appears in /data/app/com.greenlabs.smartfarm-maquPehEjhn1mslOGLCSWQ==/base.apk)
        at com.appboy.reactbridge.AppboyReactBridge.subscribeToContentCardsUpdatedEvent(AppboyReactBridge.java:691)
        at com.appboy.reactbridge.AppboyReactBridge.<init>(AppboyReactBridge.java:72)
        at com.appboy.reactbridge.AppboyReactPackage.createNativeModules(AppboyReactPackage.java:21)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1215)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1185)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1123)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:124)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:948)
        at java.lang.Thread.run(Thread.java:919)
```

But, I downgraded `com.appboy:android-sdk-ui` to 13.1.0, it seems okay.
```
// :app build.gradle
implementation "com.appboy:android-sdk-ui:13.1.0"
```

**Comment by Bucimis** [comment]
closing in favor of https://github.com/Appboy/appboy-react-sdk/issues/113

for fix, see https://github.com/Appboy/appboy-react-sdk/issues/113#issuecomment-838929828
